version: "3.8"
volumes:
  prometheus_data: {}
  grafana_data: {}
services:
  service1:
    build:
      context: .
      target: service1
      dockerfile: Dockerfile
    ports:
      - 3000:3000
  service2:
    build:
      context: .
      target: service2
      dockerfile: Dockerfile
    ports:
      - 3001:3001
  service3:
    build:
      context: .
      target: service3
      dockerfile: Dockerfile
    ports:
      - 3002:3002
  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
     - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana:3.0.0-beta7
    volumes: 
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    ports:
      - "9999:3000"